/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AnalystsAnalystIdRouteImport } from './routes/analysts.$analystId'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as SportsSportIdRouteImport } from './routes/sports.$sportId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystsAnalystIdRoute = AnalystsAnalystIdRouteImport.update({
  id: '/analysts/$analystId',
  path: '/analysts/$analystId',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SportsRoute,
} as any)
const SportsSportIdRoute = SportsSportIdRouteImport.update({
  id: '/$sportId',
  path: '/$sportId',
  getParentRoute: () => SportsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/directory': typeof DirectoryRoute
  '/lab': typeof LabRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/records': typeof RecordsRoute
  '/sports': typeof SportsRouteWithChildren
  '/verify': typeof VerifyRoute
  '/analysts/$analystId': typeof AnalystsAnalystIdRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/sports/': typeof SportsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/directory': typeof DirectoryRoute
  '/lab': typeof LabRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/records': typeof RecordsRoute
  '/verify': typeof VerifyRoute
  '/analysts/$analystId': typeof AnalystsAnalystIdRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/sports': typeof SportsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/directory': typeof DirectoryRoute
  '/lab': typeof LabRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/records': typeof RecordsRoute
  '/sports': typeof SportsRouteWithChildren
  '/verify': typeof VerifyRoute
  '/analysts/$analystId': typeof AnalystsAnalystIdRoute
  '/sports/$sportId': typeof SportsSportIdRoute
  '/sports/': typeof SportsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/directory'
    | '/lab'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/records'
    | '/sports'
    | '/verify'
    | '/analysts/$analystId'
    | '/sports/$sportId'
    | '/sports/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/directory'
    | '/lab'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/records'
    | '/verify'
    | '/analysts/$analystId'
    | '/sports/$sportId'
    | '/sports'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/directory'
    | '/lab'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/records'
    | '/sports'
    | '/verify'
    | '/analysts/$analystId'
    | '/sports/$sportId'
    | '/sports/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DirectoryRoute: typeof DirectoryRoute
  LabRoute: typeof LabRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  RecordsRoute: typeof RecordsRoute
  SportsRoute: typeof SportsRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  AnalystsAnalystIdRoute: typeof AnalystsAnalystIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysts/$analystId': {
      id: '/analysts/$analystId'
      path: '/analysts/$analystId'
      fullPath: '/analysts/$analystId'
      preLoaderRoute: typeof AnalystsAnalystIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof SportsRoute
    }
    '/sports/$sportId': {
      id: '/sports/$sportId'
      path: '/$sportId'
      fullPath: '/sports/$sportId'
      preLoaderRoute: typeof SportsSportIdRouteImport
      parentRoute: typeof SportsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SportsRouteChildren {
  SportsSportIdRoute: typeof SportsSportIdRoute
  SportsIndexRoute: typeof SportsIndexRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportIdRoute: SportsSportIdRoute,
  SportsIndexRoute: SportsIndexRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DirectoryRoute: DirectoryRoute,
  LabRoute: LabRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  RecordsRoute: RecordsRoute,
  SportsRoute: SportsRouteWithChildren,
  VerifyRoute: VerifyRoute,
  AnalystsAnalystIdRoute: AnalystsAnalystIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
